# Generated by Django 3.1.7 on 2022-02-04 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='作業概要', max_length=255, verbose_name='タイトル')),
                ('author', models.CharField(help_text='作成者', max_length=50, verbose_name='作成者')),
                ('worker', models.CharField(help_text='作業担当者', max_length=50, verbose_name='作業担当者')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('duration', models.DurationField(blank=True, default=90, help_text='HH:MM:SS', null=True, verbose_name='有効期間')),
            ],
        ),
    ]
