# Generated by Django 3.1.7 on 2022-02-04 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='duration',
        ),
    ]
